echo 1 > C:\PROJECTS\GitHub\ACTIVE_PROGRAM_USAGE_SUMMARY_SUBMITS\BlockedLines.txt
echo 2 >> C:\PROJECTS\GitHub\ACTIVE_PROGRAM_USAGE_SUMMARY_SUBMITS\BlockedLines.txt
echo 3 >> C:\PROJECTS\GitHub\ACTIVE_PROGRAM_USAGE_SUMMARY_SUBMITS\BlockedLines.txt

DEBUG=false
if ${DEBUG]; then
echo 4  >> C:\PROJECTS\GitHub\ACTIVE_PROGRAM_USAGE_SUMMARY_SUBMITS\BlockedLines.txt
echo 5  >> C:\PROJECTS\GitHub\ACTIVE_PROGRAM_USAGE_SUMMARY_SUBMITS\BlockedLines.txt
fi
echo 6  >> C:\PROJECTS\GitHub\ACTIVE_PROGRAM_USAGE_SUMMARY_SUBMITS\BlockedLines.txt
echo 7  >> C:\PROJECTS\GitHub\ACTIVE_PROGRAM_USAGE_SUMMARY_SUBMITS\BlockedLines.txt
